import pandas as pd

df2 = pd.read_csv('occupation_Cleaned_1-7.csv').dropna()
df2['MedWage'].replace('>=$208,000',208000,inplace=True)
dfgraph = df2[df2['MedWage'] != ''][df2['Code'].str[-3:] != '000']

categories = {
    'Front Line Heroes':['Registered nurses', 'Family medicine physicians', 'Firefighters',
                         'Conservation scientists', 'Epidemiologists'],
    'Best Job Ever!':['Ship and boat captains and operators', 'Actors, producers, and directors', 'Coaches and scouts',
                      'Tour and travel guides', 'Forest and conservation workers', 'Nurse midwives'],
    'Extremely Dangerous':['Electricians', 'Commercial divers', 'Animal care and service workers', 
                           'Correctional officers and jailers', 'Earth drillers, except oil and gas; and explosives workers, ordnance handling experts, and blasters'],
    'Tech Savvy':['Computer programmers', 'Software developers and software quality assurance analysts and testers',
                  'Web developers and digital interface designers', 'Atmospheric and space scientists',
                  'Computer hardware engineers', 'Medical equipment repairers', 'Technical writers'],
    'Can\'t Live Without Them':['Refuse and recyclable material collectors', 'Plumbers, pipefitters, and steamfitters',
                                'Electricians', 'Construction laborers', 'Elementary and middle school teachers',
                                'Secondary school teachers', 'Special education teachers', 'Heating, air conditioning, and refrigeration mechanics and installers',
                                'Automotive service technicians and mechanics', 'Farmworkers, farm, ranch, and aquacultural animals'],
    'Trade School Superstars':['Welders, cutters, solderers, and brazers', 'Electricians', 'Registered nurses',
                               'Plumbers, pipefitters, and steamfitters', 'Miscellaneous assemblers and fabricators'],
    'Taking Care of Business':['Accountants and auditors', 'Credit analysts', 'Insurance underwriters',
                               'Actuaries', 'Payroll and timekeeping clerks', 'Real estate brokers and sales agents',
                               'Lawyers', 'Sales representatives, wholesale and manufacturing'],
    'I Love Working Outside':['Tour and travel guides', 'Electricians', 'Farmworkers, farm, ranch, and aquacultural animals',
                              'Roofers', 'Solar photovoltaic installers', 'Brickmasons, blockmasons, and stonemasons',
                              'Wind turbine service technicians', 'Landscaping and groundskeeping workers'],
    'How Fast Can We Go?':['Airline pilots, copilots, and flight engineers', 'Commercial pilots', 'Heavy and tractor-trailer truck drivers',
                           'Locomotive engineers', 'Motorboat operators'],
    'All Kinds of Farmers':['Animal breeders', 'Agricultural equipment operators', 'Farmworkers and laborers, crop, nursery, and greenhouse',
                            'Farmworkers, farm, ranch, and aquacultural animals', 'Farm equipment mechanics and service technicians',
                            'Farmers, ranchers, and other agricultural managers'],
    'Engineers Make Things Work':['Aerospace engineers', 'Agricultural engineers', 'Bioengineers and biomedical engineers',
                                  'Chemical engineers', 'Civil engineers', 'Electrical and electronics engineers',
                                  'Mechanical engineers', 'Industrial engineers'],
    'Medical Madness':['Registered nurses', 'Family medicine physicians', 'Epidemiologists', 'Dentists',
                       'Optometrists', 'Pharmacists', 'Physician assistants', 'Anesthesiologists', 'Pediatricians, general',
                       'Surgeons, except ophthalmologists', 'Health practitioner support technologists and technicians',
                       'Home health and personal care aides', 'Veterinarians', 'Nurse midwives', 'Obstetricians and gynecologists'],
    'Weather Warriors':['News analysts, reporters, and journalists', 'Electricians', 'Emergency medical technicians and paramedics',
                        'Fishing and hunting workers', 'Line installers and repairers', 'Commercial divers',
                        'Sailors and marine oilers', 'Hydrologists'],
    'I Actually Get Paid to Do This':['Biological scientists', 'Athletes, coaches, umpires, and related workers',
                                      'Locomotive engineers', 'Clergy', 'Actors, producers, and directors',
                                      'Dancers and choreographers', 'Fashion designers'],
    'Helping Hands':['Counselors', 'Social workers', 'Directors, religious activities and education', 'Community health workers',
                     'Occupational therapists', 'Speech-language pathologists', 'Home health and personal care aides'],
    'Rich but not Famous':['Financial managers', 'Computer network architects', 'Actuaries', 'Dentists',
                           'Physician assistants', 'Nurse anesthetists', 'Anesthesiologists', 
                           'Airline pilots, copilots, and flight engineers', 'Air traffic controllers']
}
